name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DOCKER_BACKEND_IMAGE: lukeecheng/mern-backend
  DOCKER_FRONTEND_IMAGE: lukeecheng/mern-frontend

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Generate build ID
      id: prep
      run: |
        branch=${GITHUB_REF##*/}
        sha=${GITHUB_SHA::8}
        ts=$(date +%s)
        echo "BUILD_ID=${branch}-${sha}-${ts}" >> $GITHUB_ENV

    - name: Build and push backend image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: true
        tags: |
          ${{ env.DOCKER_BACKEND_IMAGE }}:${{ env.BUILD_ID }}
          ${{ env.DOCKER_BACKEND_IMAGE }}:rebuild

    - name: Build and push frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: true
        tags: |
          ${{ env.DOCKER_FRONTEND_IMAGE }}:${{ env.BUILD_ID }}
          ${{ env.DOCKER_FRONTEND_IMAGE }}:rebuild 